language: rust
rust:
  - 1.31.1
  - stable
  - beta
  - nightly
matrix:
  include:
    - os: osx
      osx_image: xcode11
      rust: stable
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - libgexiv2-dev
  homebrew:
    packages:
      - gexiv2
script:
  - |
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
      fi
      cargo build --verbose
      cargo test --verbose
notifications:
  email:
    on_success: never
dist: xenial
