name: build
on:
  pull_request:
  push:
    branches: ["main"]
permissions:
  contents: read
concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  linux:
    strategy:
      matrix:
        os_image: ["ubuntu-latest", "ubuntu-24.04-arm"]
        container_image: ["rust:1.70-slim", "rust:slim", "rustlang/rust:nightly-slim"]
    runs-on: ${{ matrix.os_image }}
    container:
      image: ${{ matrix.container_image }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          apt --quiet update
          apt --yes install libgexiv2-dev
      - name: Show environment info
        run: |
          rustc --version --verbose && echo ""
          cargo --version --verbose && echo ""
          dpkg --list libgexiv2-dev libexiv2-dev
      - name: Build
        run: cargo build --verbose --all-features
      - name: Test
        run: cargo test --verbose --all-features
      - name: Run Examples
        run: |
          cargo run --example open_buf
          cargo run --features raw-tag-access --example raw_tag_access
          cargo run --features xmp-packet-access --example xmp_packet_access
  osx:
    runs-on: macos-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: brew install gexiv2
      - name: Install Rust and Cargo
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Show environment info
        run: |
          rustc --version --verbose && echo ""
          cargo --version --verbose
      - name: Build
        run: cargo build --verbose --all-features
      - name: Test
        run: cargo test --verbose --all-features
      - name: Run Examples
        run: |
          cargo run --example open_buf
          cargo run --features raw-tag-access --example raw_tag_access
          cargo run --features xmp-packet-access --example xmp_packet_access
